"""clubs table

Revision ID: 13aea335c2d5
Revises: 
Create Date: 2021-05-25 11:14:22.502809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13aea335c2d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelName', sa.String(length=120), nullable=True),
    sa.Column('clubType', sa.String(length=120), nullable=True),
    sa.Column('brandName', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clubs')
    # ### end Alembic commands ###
