"""empty message

Revision ID: 93ec0eeae4f2
Revises: 13aea335c2d5
Create Date: 2021-06-07 19:13:16.876542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ec0eeae4f2'
down_revision = '13aea335c2d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bagName', sa.String(length=120), nullable=True),
    sa.Column('club1', sa.Integer(), nullable=True),
    sa.Column('club2', sa.Integer(), nullable=True),
    sa.Column('club3', sa.Integer(), nullable=True),
    sa.Column('club4', sa.Integer(), nullable=True),
    sa.Column('club5', sa.Integer(), nullable=True),
    sa.Column('club6', sa.Integer(), nullable=True),
    sa.Column('club7', sa.Integer(), nullable=True),
    sa.Column('club8', sa.Integer(), nullable=True),
    sa.Column('club9', sa.Integer(), nullable=True),
    sa.Column('club10', sa.Integer(), nullable=True),
    sa.Column('club11', sa.Integer(), nullable=True),
    sa.Column('club12', sa.Integer(), nullable=True),
    sa.Column('club13', sa.Integer(), nullable=True),
    sa.Column('club14', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bags')
    # ### end Alembic commands ###
