"""empty message

Revision ID: c9974ab42a4a
Revises: d3c3a22f146d
Create Date: 2021-07-01 13:54:55.890811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9974ab42a4a'
down_revision = 'd3c3a22f146d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bags', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bags', type_='foreignkey')
    # ### end Alembic commands ###
