"""empty message

Revision ID: d3c3a22f146d
Revises: cbb3ff8cd148
Create Date: 2021-07-01 13:31:31.722189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c3a22f146d'
down_revision = 'cbb3ff8cd148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bagitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bags', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bags', 'users', ['user_id'], ['id'])
    op.drop_column('bags', 'club6')
    op.drop_column('bags', 'club5')
    op.drop_column('bags', 'club8')
    op.drop_column('bags', 'club1')
    op.drop_column('bags', 'club3')
    op.drop_column('bags', 'club7')
    op.drop_column('bags', 'club12')
    op.drop_column('bags', 'club13')
    op.drop_column('bags', 'club14')
    op.drop_column('bags', 'club9')
    op.drop_column('bags', 'club4')
    op.drop_column('bags', 'club10')
    op.drop_column('bags', 'club2')
    op.drop_column('bags', 'club11')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bags', sa.Column('club11', sa.INTEGER(), nullable=True))
    op.add_column('bags', sa.Column('club2', sa.INTEGER(), nullable=True))
    op.add_column('bags', sa.Column('club10', sa.INTEGER(), nullable=True))
    op.add_column('bags', sa.Column('club4', sa.INTEGER(), nullable=True))
    op.add_column('bags', sa.Column('club9', sa.INTEGER(), nullable=True))
    op.add_column('bags', sa.Column('club14', sa.INTEGER(), nullable=True))
    op.add_column('bags', sa.Column('club13', sa.INTEGER(), nullable=True))
    op.add_column('bags', sa.Column('club12', sa.INTEGER(), nullable=True))
    op.add_column('bags', sa.Column('club7', sa.INTEGER(), nullable=True))
    op.add_column('bags', sa.Column('club3', sa.INTEGER(), nullable=True))
    op.add_column('bags', sa.Column('club1', sa.INTEGER(), nullable=True))
    op.add_column('bags', sa.Column('club8', sa.INTEGER(), nullable=True))
    op.add_column('bags', sa.Column('club5', sa.INTEGER(), nullable=True))
    op.add_column('bags', sa.Column('club6', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'bags', type_='foreignkey')
    op.drop_column('bags', 'user_id')
    op.drop_table('bagitem')
    # ### end Alembic commands ###
